### DISCUSSION TITLE
Component proposal: Step indicator vertical variant

### DISCUSSION THREAD

**Discussion by jcandan** [uswds/uswds#5961] [Proposals]
### Component name

[Step indicator](https://designsystem.digital.gov/components/step-indicator)

### Component description

The steps are displayed vertically.

![image](https://github.com/uswds/uswds/assets/2332648/ac705478-8e66-4f13-9417-e04ce12a4641)

### Why USWDS needs this component

When a the number of steps exceeds what can appropriately fit horizontally, the steps should be able to be displayed vertically.

**Comment by jcandan** [comment]
It would be nice to see this work in conjunction with https://github.com/uswds/uswds/discussions/5960.

**Comment by jcandan** [comment]
Got fairly quick results with the Default via:

```scss
.usa-step-indicator--vertical
  .usa-step-indicator__segments {
      display: block;
  }

  .usa-step-indicator__segment:after {
      position: relative;
  }
}
```

![image](https://github.com/uswds/uswds/assets/2332648/ac705478-8e66-4f13-9417-e04ce12a4641)

A little more work is needed.
