### ISSUE TITLE
The header should support a logo image

### ISSUE THREAD

**Issue by shawnbot** [uswds/uswds#1594]
Currently our header doesn't offer any guidance for where to place a logo, how big it should be, or anything like that. I imagine that many government agencies would like to be able to put a logo next to their name, and it would be nice if they could do that without having to twiddle with `width` and `height` attributes in the HTML—in other words, if we sized it reasonably/appropriately in CSS.

**Comment by guitarzan** [comment]
I'm glad you're addressing this! We've recently wrestled with adding a logo to USWDS to comply with our agency co-branding standards. Here's what we came up with. It's working well for us, but I'd appreciate your input.

SCSS: 

```scss
.usa-header-basic {
    .gaepd-logo {
    @include media($nav-width) {
      bottom: 0;
      position: relative;
    }
  }
  .gaepd-navbar {
    @include media($nav-width) {
      width: auto;
    }
  }
}
.gaepd-logo-link {
    display: flex;
    align-items: center;
}
.gaepd-logo-link img {
    width: 3rem;
    margin-right: 1rem;

    @include media($nav-width) {
        width: 8rem; 
        margin: 1rem 2rem 1rem 0;
    }
}
```

HTML: 

```html
    <header class="usa-header usa-header-basic" role="banner">
        <div class="usa-nav-container">
            <div class="usa-navbar gaepd-navbar">
                <button class="usa-menu-btn">Menu</button>
                <div class="usa-logo gaepd-logo" id="logo">
                    <em class="usa-logo-text">
                        <a accesskey="1" title="Home" aria-label="Home" class="gaepd-logo-link" href="/">
                            <img src="/assets/logos/epd-icon.svg" alt="" /> Environmental Protection Division
                        </a>
                    </em>
                </div>
            </div>
            <nav role="navigation" class="usa-nav">
                <button class="usa-nav-close">
                    <img src="/assets/img/close.svg" alt="close">
                </button>
                <ul class="usa-nav-primary usa-accordion">
                    <li>
                        <a title="Home" aria-label="Home" href="/">Home</a>
                    </li>
                    <li class="js-search-button-container">
                        <a class="usa-header-search-button js-search-button" href="/Search">Search</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
```

And here is how it looks on desktop/mobile:
![image](https://cloud.githubusercontent.com/assets/737326/25093699/662a11d2-2361-11e7-8986-6dc2959f25b2.png)
![image](https://cloud.githubusercontent.com/assets/737326/25093708/73253dbc-2361-11e7-8217-85fffd841168.png)
