### ISSUE TITLE
Simplify Sass path variable overrides

### ISSUE THREAD

**Issue by shawnbot** [uswds/uswds#1797]
Currently it's necessary to set two different variables to change the path to the font and image files relative to the CSS output path. For instance, if you were to copy the whole `dist` directory to your project's `assets/uswds` directory and wanted your custom CSS to live in `assets/css/main.css`, like so:

```
assets/
├── css/
│   └── main.css
└── uswds
    ├── css/
    ├── img/
    ├── fonts/
    └── ...
```

Then the Sass that generates `assets/css/main.css` would need to do something like this:

```scss
$font-path: '../uswds/fonts';
$img-path: '../uswds/img';

@import 'path/to/uswds/all';
```

This feels redundant and a bit silly. I think that we can simplify this for users by introducing a new variable that establishes the USWDS base path under which we'd expect to find `fonts` and `img` directories:

```scss
$uswds-path: '../' !default;
$font-path: '#{$uswds-path}fonts' !default;
$img-path: '#{$uswds-path}img' !default;
```

This way, you can just override `$uswds-path`, and both `$font-path` and `$img-path` will by default be set to the respective expected paths.
