### ISSUE TITLE
Leaflet control bug

### ISSUE THREAD

**Issue by EricSchles** [uswds/uswds#1919]
## Description

I expected to get the following functionality:

<img width="705" alt="screen shot 2017-05-09 at 10 15 42 am" src="https://cloud.githubusercontent.com/assets/928957/25855205/8331ef3e-34a0-11e7-8904-5ebf0ee53ea5.png">

notice the top right corner - where there are little radio buttons next to the options and check boxes in the area below.

This is what happens when I include uswds:

<img width="704" alt="screen shot 2017-05-09 at 10 16 55 am" src="https://cloud.githubusercontent.com/assets/928957/25855253/a9b2163e-34a0-11e7-971f-2a4bb733d404.png">

Notice the radio buttons are removed and so is the checkbox.  Also the spacing is all funky.

I am using uswds-1.0.0

## Steps to reproduce the issue

1. `git clone https://github.com/18F/permit-finder`
2.  cd into the repo and run `make all # this downloads the data`
3. start the server - `yarn start:dev`
4. head to http://localhost:8000

## Additional information [optional]

* Relevant research and support documents
* Screen shot images
* Notes
* And so on

**Comment by shawnbot** [comment]
Oof, yeah. I'm running the app locally and don't see the layer control, so I can't debug it directly. But if I were to guess, I would assume that this is an issue of the Standards CSS applying styles to `<label>` that aren't friendly to Leaflet's markup. However, I did visit [Leaflet's demo page](http://leafletjs.com/examples/layers-control/) and added the Standards CSS with this JS snippet:

```js
javascript:(function(){var s=document.createElement('link');s.rel='stylesheet';s.href='https://unpkg.com/uswds@1.1.0/dist/css/uswds.min.css';document.head.appendChild(s);})();
```

and I'm not seeing that issue:

![image](https://cloud.githubusercontent.com/assets/113896/25867231/ca6d8982-34ad-11e7-9c76-365f07f82249.png)

@EricSchles can you deploy the app to your cloud.gov sandbox so I can see what you're seeing?

**Comment by EricSchles** [comment]
@shawnbot Here ya go: permit-finder-v02.app.cloud.gov

**Comment by shawnbot** [comment]
Okay, so I was right: this is an incompatibility between the Standards CSS and Leaflet's controls. The `<label>` elements have `margin-top: 3rem` (which seems _really_ big!) and the radio inputs themselves are hidden

![image](https://cloud.githubusercontent.com/assets/113896/25962441/ad2066c0-3632-11e7-92eb-0ea57dc01da7.png)

I was able to get it looking (mostly) right by disabling a bunch of our CSS rules:

![image](https://cloud.githubusercontent.com/assets/113896/25962633/52c60148-3633-11e7-92a4-a7b8988707b4.png)

In other words, I think that you could add the following CSS to override this behavior in another stylesheet referenced after `uswds.css`:

```css
.leaflet-control label {
  margin-top: initial;
}

.leaflet-control input[type=radio] {
  appearance: initial;
  -moz-appearance: initial;
  -webkit-appearance: initial;
  display: initial;
  height: initial;
  margin: 2px initial initial;
  opacity: 1;
  outline: initial;
  padding: initial;
  position: initial;
  width: initial;
}
```

Can you try this and let us know how it goes, @EricSchles? 🤞
