### ISSUE TITLE
[grid issues] 1/4 and 3/4 grid columns are broken at 600px break point

### ISSUE THREAD

**Issue by kyle-jennings** [uswds/uswds#1954]
## Description

Looking at the compiled CSS found over at [standards.usa.gov](https://github.com/18F/web-design-standards/releases/download/v1.1.0/uswds-1.1.0.zip), at 600px usa-wide-one-fourth and usa-wide-three-fourths are set to 47% and 100% respectively (the other columns look correct at a quick glance):

  ```
@media screen and (min-width: 600px) {
...
...
...
.usa-width-one-fourth {
    float: left;
    display: block;
    margin-right: 4.82916%;
    width: 47.58542%;
  }
  .usa-width-one-fourth:last-child {
    margin-right: 0;
  }
  .usa-width-one-fourth:nth-child(2n) {
    margin-right: 0;
  }
  .usa-width-three-fourths {
    float: left;
    display: block;
    margin-right: 4.82916%;
    width: 100%;
  }
...
...
...
}
```

**Comment by donjo** [comment]
@kyle-jennings Thanks Kyle, I looked at the source in `_grid.scss` and it looks like it generated the right thing based on the rules but I'm not sure the rules are correct. Like should one-fourth span more columns than one-third? I'll try to figure out the history around these decisions.

```css
@include media($medium) {
  .usa-width-one-whole {
    @include span-columns(6);
  }

  .usa-width-one-half {
    @include span-columns(3);
  }

  .usa-width-one-third {
    @include span-columns(2);
  }

  .usa-width-two-thirds {
    @include span-columns(4);
  }

  .usa-width-one-fourth {
    @include span-columns(3);

    &:nth-child(2n) {
      margin-right: 0;
    }
  }

  .usa-width-three-fourths {
    @include span-columns(6);
  }
```
