### ISSUE TITLE
Allow custom namespace by authors

### ISSUE THREAD

**Issue by joshbruce** [uswds/uswds#2153]
For those using the raw Sass, it might be desirable to change the namespace for the project (could also reduce adoption friction, so to speak). For example, being able to replace `usa-` with `mine-`. Add `$namespace: 'usa-';` to `variables.scss`. Prefix classes with `#{$namespace}`. Now, when releases are made to the USWDS, those of us who are, more or less, extending can just upgrade along with everyone while maintaining our own namespace for custom things. (Developers also don't have to know which elements have been put under the custom namespace versus not really.)

## Real world

I use a lot of the base styles and patterns for my own project. Extending with Font Awesome and some custom HTML + CSS patterns. Having said that, I prefix all my classes with `ef-`, which can make it difficult to upgrade to the latest USWDS.

I am looking for packages that will do find and replace via gulp but thought it might worthwhile to come to the source. Further, creating a more`@mixin` based approach is also viable; however, I remember @msecret saying there have been issues there as well.

Note: This would also match the pattern used in the Javascript. 

## Packages

- https://github.com/johnotander/gulp-class-prefix: Add prefix to classes in Sass. (Does not appear to replace class prefixes already in place.)
- https://github.com/lazd/gulp-replace: "Easily" do find and replace.

Maybe strip `usa-` from all classes and ids - then make class-prefix part of the build step. Compiled package maintains `usa-` prefix, but individual Sass is "clean".

**Comment by joshbruce** [comment]
Heading down the demo trail as I get the opportunity to slow down and revisit my own style library... :)

https://github.com/8fold/8fold-web-assets/blob/develop/config/gulp/stylesheets.js - gulp tasks

https://github.com/8fold/8fold-web-assets/blob/develop/config/gulp/environmental.js - the method that actually does the find, replace, save.

https://github.com/8fold/8fold-web-assets/blob/develop/src/stylesheets/components/_alerts.scss - not replace `$usa` variable prefixes at this time.

https://github.com/8fold/8fold-web-assets/blob/develop/src/stylesheets/core/_variables.scss - now you can set a prefix variable in `_variables.scss` and have your namespace compiled into the final CSS.

Compiled output:

```css
.ef-accordion-button[aria-expanded=false] {
  background-image: url("../img/plus.png");
  background-image: url("../img/plus.svg");
  background-repeat: no-repeat;
  background-size: 1.5rem;
}

.ef-alert {
  background-color: #f1f1f1;
  background-position: 2rem 2rem;
  background-repeat: no-repeat;
  background-size: 5.2rem;
  padding-bottom: 1.4rem;
  padding-left: 3rem;
  padding-right: 2rem;
  padding-top: 2rem;
  position: relative;
}

.ef-alert::before {
  background-color: #8b8b8b;
  content: '';
  height: 100%;
  left: 0;
  position: absolute;
  top: 0;
  width: 1rem;
}
```
