### ISSUE TITLE
Consider using newer CSS3 properties for font-feature-settings

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2655]
```css
font-variant-ligatures: common-ligatures;
font-variant-caps: small-caps;
font-variant-alternates: styleset(1);
```

or 

```css
[existing font-feature-settings rule...]

@supports (font-variant-ligatures: common-ligatures) {
  font-feature-settings: normal;
  font-variant-ligatures: common-ligatures;
}
```

Browser support and implementation considerations?
