### ISSUE TITLE
Footer issues

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3124]
See https://designsystem.digital.gov/components/footer/

<img width="945" alt="Screen Shot 2019-10-03 at 12 31 04 PM" src="https://user-images.githubusercontent.com/11464021/66157958-b80c7980-e5d9-11e9-8893-dd10a9dd5348.png">

- [ ] We explicitly add a `mobile-lg:grid-gap-0` to the contact info grid, but that seems to be a mistake.

- - -

- [ ] If utilities aren't set to use important `usa-footer__contact-info.grid-row` will be overridden CSS to `display: inline-block` — we need to constrain this behavior to the slim footer only.

- - -

- [ ] `.usa-footer__logo-img` needs an explicit `width: 100%`set

- - -

- [ ] Big footer open carets are too big after svg refresh...

<img width="370" alt="Screen Shot 2019-10-03 at 2 19 08 PM" src="https://user-images.githubusercontent.com/11464021/66165091-d4fc7900-e5e8-11e9-881d-1625277e9290.png">

- - -

- [ ] Big footer should be able to accept nav items that don't contain sub-items, just as the primary nav can be a combination of simple links and links that trigger menus.

- - -

- [ ] Use `auto` for default footer link spacing `@desktop` to improve horizontal spacing

<img width="1020" alt="Screen Shot 2019-10-03 at 3 35 58 PM" src="https://user-images.githubusercontent.com/11464021/66168928-86081100-e5f3-11e9-8d6e-332d13e72e74.png">

**Comment by mejiaj** [comment]
> If utilities aren't set to use important usa-footer__contact-info.grid-row will be overridden CSS to display: inline-block — we need to constrain this behavior to the slim footer only.

Just to confirm this means:
```css
.usa-footer__contact-info {
    display: inline-block;
    line-height: 1.1;
}
```

Should be:
```css
.usa-footer__contact-info {
 ... all current styles minus `display: inline-block;`
}

.usa-footer--slim .usa-footer__contact-info {
  display: inline-block;
}
```

--- 

>.usa-footer__logo-img needs an explicit width: 100%set

What issue is this causing and where? I assume this is an IE11 issue?
