### ISSUE TITLE
Fractal is incorrectly outputting info and success alerts

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3387]
Fractal is misconfigured and has the wrong `name` value for the info and success alerts. This means that when we target the `info` alert in `uswds-site`, we actually get the success alert.

```
  - name: default <-- let's use info here and not default
    label: Info
    context:
      alert:
        classes: "usa-alert--info"
        title: Informative status

  - name: info <-- this should be success
    label: Success
    context:
      alert:
        classes: "usa-alert--success"
        title: Success status
```
