### ISSUE TITLE
Chevron icon display on .usa-banner__button::after broken

### ISSUE THREAD

**Issue by matthopson** [uswds/uswds#3552]
## Description

It appears some banner svg changes have added some extra styles that conflict with the chevron icon on `.usa-banner__button::after`. I've downgraded and it fixes the issue, and have also taken screenshots of both the display and compiled CSS for these.

### 2.7.x ###
<img width="266" alt="Screen Shot 2020-07-14 at 10 06 22 AM" src="https://user-images.githubusercontent.com/1891789/87449702-bfc26b00-c5ba-11ea-90ac-d7a503994d17.png">
<img width="419" alt="Screen Shot 2020-07-14 at 10 06 33 AM" src="https://user-images.githubusercontent.com/1891789/87449718-c3ee8880-c5ba-11ea-9561-89c758374aa8.png">

### 2.8.0 ###
<img width="305" alt="Screen Shot 2020-07-14 at 9 57 17 AM" src="https://user-images.githubusercontent.com/1891789/87449749-d1a40e00-c5ba-11ea-8e0e-0cd08dc79465.png">
<img width="417" alt="Screen Shot 2020-07-14 at 10 10 12 AM" src="https://user-images.githubusercontent.com/1891789/87449766-d5379500-c5ba-11ea-93e7-6b046b99e0c3.png">

And here's a little snippet on how this is being used:
```
<button
  aria-controls="gov-banner"
  aria-expanded={!!showUsaBannerDetails}
  className="usa-accordion__button usa-banner__button"
  onClick={() => toggleUsaBannerDetailsSequence()}
>
    <span className="usa-banner__button-text">
      Here’s how you know
    </span>
</button>
```

**Comment by kkoskelin** [comment]
I've seen this behavior in both Chrome and Safari.  Firefox appears to not exhibit this rendering behavior.

**Comment by mejiaj** [comment]
I'm unable to reproduce in Chrome 84.0.4147.89 OSX. How are you compiling the SCSS?

It looks like you're missing the prefix:
![image](https://user-images.githubusercontent.com/3385219/87453103-a673eb80-c5c7-11ea-9ab8-dfd1e907257c.png)

```scss
@media (min-width: 40em)
.usa-banner__button::after {
  background: 0 0;
  background-color: #005ea2;
  -webkit-mask: url(../img/chevron.svg) no-repeat center/1.3128205128ex .8ex;
  mask: url(../img/chevron.svg) no-repeat center/1.3128205128ex .8ex;
}
```
