### ISSUE TITLE
Create a  LinkedIn icon

### ISSUE THREAD

**Issue by shawndwells** [uswds/uswds#4176]
**Is your feature request related to a problem? Please describe.**
When using the icon components at https://designsystem.digital.gov/components/icon/, there is no option for LinkedIn.

**Describe the solution you'd like**
Create icon for LinkedIn

**Describe alternatives you've considered**
* Hard coding an image, but then it breaks with the overall look/feel of the design system.
* Perhaps a custom "img URL" field could be added?

**Additional context**
Code to replicate:
```
contact:
  # Configuration for social media links
  # Comment out links you don't want to use (RSS is an example)
  social_links:
    - text: Facebook
      href: https://facebook.com/CrowdStrike
      external: true
      type: facebook
    - text: Twitter
      href: https://twitter.com/CrowdStrike
      external: true
      type: twitter
    - text: YouTube
      href: https://www.youtube.com/channel/UCsRdY9CtEVWTNO4ulwfzqVA
      external: true
      type: youtube
    - text: LinkedIn
      href: https://www.linkedin.com/company/CrowdStrike
      external: true
      type: linkedin
    - text: Instagram
      href: https://www.instagram.com/crowdstrike/?hl=en
      external: true
      type: Instagram
```

which generates:
![image](https://user-images.githubusercontent.com/5713754/116490328-14428880-a865-11eb-82d8-2f210e3c9699.png)
