### ISSUE TITLE
Utilizing CSS variables

### ISSUE THREAD

**Issue by morganspencerdev** [uswds/uswds#4644]
**Is your feature request related to a problem? Please describe.**

The CSS styles currently have some limitations, mainly that SASS is required for customization with the tokens and many other features. This tends to overcomplicate things when implementing the styles.

**Describe the solution you'd like**

Now that support for IE11 has been dropped in version 3.0, I'm proposing the use of CSS variables to simplify implementation and improve customization. Many modern frameworks utilize the robustness of these variables to provide flexibility both in development and to end users.

This would, of course, be a large undertaking and some things cannot be solved fully with this solution. However, I think it provides great benefits to users of USWDS.

I'm happy to assist and I can even make a small mockup of the proposed solution if that might help.

**Describe alternatives you've considered**

I haven't found an alternative that would provide the same flexibility and customization that CSS variables would.

**Additional context**

CSS variables support: https://caniuse.com/css-variables

**Comment by mejiaj** [comment]
Hey @morganmspencer, thanks for submitting this issue!

Could you explain a bit more on how CSS variables would simplify implementing styles? Do you mean that we'd get rid of the SASS requirement? We'd need to make sure this proposal covers the browsers above 2% in https://analytics.usa.gov/

A small mockup of the proposed solution would be helpful.

**Comment by esheehan-gsl** [comment]
I'd love to see the design tokens provided as CSS custom properties similarly to how [Open Props](https://open-props.style/) is structured. It'd be really handy to be able to load a couple of CSS files to use the tokens without having to set up Sass. A person could then build off of the USWDS tokens without opting in to all of the components simply by importing the relevant custom props CSS.

**Comment by CullenJWebb** [comment]
I strongly support this suggestion.

SASS is the best way to customize a front-end framework like this but sometimes that is unfortunately not an option. Just recently I was working with a team on a project and we were restricted to vanilla CSS (for silly reason, admittedly). 

There are other benefits , such as easier theming with tools such as the new WordPress Site Editor. With block based themes being able to edit vanilla CSS variables on the fly, but not SASS, they are presently locked out of USWDS customization.

It also unlocks more granular control with vanilla CSS. Similar to editing the variables with :root we could also/instead use a .modifier class and only change the variables in specific circumstances:

```
/* User defined variables */
:root {
    /* Replaces USWDS defined variable value */
    --usa-theme-color__info: var(--usa-color__blue-cool-30v);
}

/* Dark Mode */
.dark {
    /* Replaces user defined variables when class detected */
    --usa-theme-color__info: var(--usa-color__blue-cool-90);
}
```

Bootstrap v5 made this exact update and it was a tremendous help to those of us who could not get a team to migrate to SASS.

The only downsides I can think of:
- This may be a breaking change depending on implementation
- This may result in more sites loading the full USWDS package instead of trimming it down

**Comment by fulldecent** [comment]
The way that Bootstrap 5 has implemented CSS variables was also incremental. For example, see how variables applies to buttons versus shadows. We don't need to wait for a major version to start this, and we don't need to get it all done at once.

Luckily, browsers have great web inspectors which can show you applicable styles. And this can be self-documenting. This is a great way to study the mechanics with something like BS that uses this indirect approach.

As a minor excerpt of how [BS](https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css) works, see this styling in CSS-land for `.btn-primary`:

```css
.btn-primary {
  --bs-btn-color: #fff;
  --bs-btn-bg: #0d6efd;
  --bs-btn-border-color: #0d6efd;
  --bs-btn-hover-color: #fff;
  --bs-btn-hover-bg: #0b5ed7;
  --bs-btn-hover-border-color: #0a58ca;
  --bs-btn-focus-shadow-rgb: 49, 132, 253;
  --bs-btn-active-color: #fff;
  --bs-btn-active-bg: #0a58ca;
  --bs-btn-active-border-color: #0a53be;
  --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
  --bs-btn-disabled-color: #fff;
  --bs-btn-disabled-bg: #0d6efd;
  --bs-btn-disabled-border-color: #0d6efd;
}
```

As you can see it does not actually set any styles directly. So when you style with `.btn .btn-primary`, you set the styles (`.btn`) and then in the values (`.btn-primary`).

I hope this explanation helps and we can agree on a plan of which parts can implement variables in the next patch version or what needs to be held off as a breaking change.
