### ISSUE TITLE
USWDS - Bug: shadow function is missing

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#5755]
### Describe the bug

Using shadow function `shadow()` does not compile.

Followed guidance from website: [Shadow | U.USWDS)](https://designsystem.digital.gov/design-tokens/shadow/#using-shadow-tokens-2)

### Steps to reproduce the bug

1. In SCSS file, call `@use "uswds-core" as *;`.
2. Use shadow function; `box-shadow: shadow(2);`.
3. Look at compiled CSS.
4. Confirm it's not compiling.

### Expected Behavior

Given ``box-shadow: shadow(2);` I should get a CSS file with `box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.1)`.

### Related code

```scss
.site-header {
  background-color: color("white");
  box-shadow: shadow(1); // ! This doesn't compile.
  padding-top: units(3);
  padding-bottom: units(3);
}
```

### Screenshots

<img width="300" alt="image" src="https://github.com/uswds/uswds/assets/3385219/3a890f21-923e-4e61-bd09-ba0807173c17">

### System setup

- USWDS 3.7.1
- MacOS Sonoma
- Chromium 121

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.
