### ISSUE TITLE
USWDS - Sass 2.0.0: Mixed declarations deprecation

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds#5980]
## Description

Updating `sass` package to `>= 1.77.7` produces the following warnings:

```sh
DEPRECATION WARNING: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls
```

In a future release, Dart Sass will change to match the ordering produced by native CSS nesting.

This warning currently appears over 400 times. We should:
- Consider how this might affect USWDS output CSS
- Test to prevent regressions
- Consider other implications of the change.

## Additional information

Additional information on the Sass documentation page: 
[Breaking Change: Mixed Declarations](https://sass-lang.com/documentation/breaking-changes/mixed-decls/)

### Before

```scss
//
// SCSS
//
.example {
  color: red;

  a {
    font-weight: bold;
  }

  font-weight: normal;
}

//
// CSS output
//
.example {
  color: red;
  font-weight: normal;
}

.example a {
  font-weight: bold;
}
```

### Upcoming change

Declarations are implemented in the order they appear in stylesheet.

```scss

// SCSS

.example {
  color: red;

  a {
    font-weight: bold;
  }

  font-weight: normal;
}

// CSS output

.example {
  color: red;
}

.example a {
  font-weight: bold;
}

.example {
  font-weight: normal;
}
```

## How it impacts us

There's a lot of noise being generated (400+ warnings), but it's usually the same mixins popping up. If we can address it in the mixin itself we could lower the LOE.

In general, we'll have to start wrapping styles in mixins with` & { }`.

**Main mixins causing this issue**

These mixins are used many times and are causing the majority of the warnings.

- icon.scss
- button-unstyled.scss
- general/table.scss
- helpers/at-media.scss

To a lesser degree:
- alert-status-styles.scss
- add-background-svg.scss
- set-link-from-bg.scss
- set-text-from-bg.scss
- add-aspect.scss
- utilities/_font.scss
- typeset.scss
- utilities/_disabled.scss

## Solutions

We can adopt and test this new behavior early by wrapping nested declarations in mixins with `& {}`. The caveat is that the selectors are duplicated on output.

Recommendations from SASS lead:

>Specifically:
>
>- Declarations directly within mixins should be wrapped in & {} (for now) if there's any chance that the mixins will be included after nested rules (which will be the case for most mixins). It's better to write this once, in the mixin, rather than adding it as a wrapper around the mixin everywhere it's called.
>- Prefer moving declarations before mixins to wrapping them in & {}. This preserves the existing behavior, and won't need to be removed later once we're CSS-compatible.

Source: https://github.com/sass/dart-sass/issues/2276#issuecomment-2284660450

**Example of output**

```scss

// SCSS

.example {
  color: red;

  a {
    font-weight: bold;
  }

  & {
    font-weight: normal;
  }
}

// CSS output

.example {
  color: red;
}
.example a {
  font-weight: bold;
}
.example {
  font-weight: normal;
}
```
