### ISSUE TITLE
USWDS - Feature: File input support for translated strings

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#6206]
### Is your feature request related to a problem? Please describe.

File input has hardcoded strings in English, which makes it difficult for localization.

### Describe the solution you'd like

Component should support custom translated strings.

### Additional context

Related to #3445.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [x] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by amyleadem** [comment]
We should keep this issue in mind as we explore solutions in #5616. The strings currently are fairly complex to translate. When we work on #5616, we should see if we can simplify the language structure to be more easily translatable. 

Marking this issue as on hold pending the update in #5616.

**Comment by mgifford** [comment]
Just looking at:
https://designsystem.digital.gov/components/file-input/

Comparing it with UK's GDS:
https://design-system.service.gov.uk/components/file-upload/

But also with what I know about how this works in Drupal.

I think that the easiest way to do this wouldn't be in the design system as such. You would want to extract the language metadata from the file (assuming it is a .docx or .pdf file) and then associate that metadata with the file. Other metadata could be the date, title, file size.

In looking at this with Gemini, maybe creating a `locales.yaml` with

```
en:
  file-input:
    instructions: "Drag file here or choose from folder"
    no-file: "No file selected"
    change-file: "Change file"
  search:
    placeholder: "Search"

es:
  file-input:
    instructions: "Arrastre el archivo aquí o elíjalo de una carpeta"
    no-file: "Ningún archivo seleccionado"
    change-file: "Cambiar archivo"
  search:
    placeholder: "Buscar"

fr:
  file-input:
    instructions: "Glissez le fichier ici ou choisissez dans un dossier"
    no-file: "Aucun fichier sélectionné"
    change-file: "Modifier le fichier"
```



Which could then be called by:

```
<input{{ attributes.addClass(classes) }} 
  data-instructions="{{ 'Drag file here or choose from folder'|t }}"
  data-no-file="{{ 'No file selected'|t }}"
  data-change-file="{{ 'Change file'|t }}"
/>
```

We'd need a uswds-file-input-i18n.js

```
/**
 * USWDS File Input Localization Polyfill
 * Framework-agnostic version for vanilla JS/USWDS setups.
 */
(() => {
  const initFileInputLocalization = () => {
    // Find all raw file inputs matching the USWDS class
    const fileInputs = document.querySelectorAll('.usa-file-input');
    
    fileInputs.forEach((input) => {
      // Prevent running multiple times if the script is loaded twice
      if (input.dataset.i18nProcessed === 'true') return;

      // Extract the translated strings from the data-attributes
      // Fallback to the USWDS English defaults if the attributes aren't provided
      const instructions = input.getAttribute('data-instructions') || "Drag file here or choose from folder";
      const noFile = input.getAttribute('data-no-file') || "No file selected";
      const changeFile = input.getAttribute('data-change-file') || "Change file";

      // Bind them directly to the dataset properties that the component looks for
      input.dataset.instructions = instructions;
      input.dataset.noFile = noFile;
      input.dataset.changeFile = changeFile;

      // Mark as processed
      input.dataset.i18nProcessed = 'true';
    });
  };

  // Run as soon as the DOM is ready, right before USWDS kicks in
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initFileInputLocalization);
  } else {
    initFileInputLocalization();
  }
})();
```

This definitely needs more testing but might address this issue.
